/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.security;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import studio.ikara.security.jooq.security.tables.SecurityUserAuthorities;


/**
 * A class modelling indexes of tables in security.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index UK1_USER_AUTHORITIES_USER_ID_AUTHORITY_ID = Internal.createIndex(DSL.name("uk1_user_authorities_user_id_authority_id"), SecurityUserAuthorities.SECURITY_USER_AUTHORITIES, new OrderField[] { SecurityUserAuthorities.SECURITY_USER_AUTHORITIES.USER_ID, SecurityUserAuthorities.SECURITY_USER_AUTHORITIES.AUTHORITY_ID }, true);
}
