/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.security;


import org.jooq.Configuration;
import org.jooq.Field;

import studio.ikara.security.jooq.security.routines.SecurityGetCustomEpoch;
import studio.ikara.security.jooq.security.routines.SecurityNextId;


/**
 * Convenience access to all stored procedures and functions in security.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>security.security_get_custom_epoch</code>
     */
    public static Long securityGetCustomEpoch(
          Configuration configuration
    ) {
        SecurityGetCustomEpoch f = new SecurityGetCustomEpoch();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>security.security_get_custom_epoch</code> as a field.
     */
    public static Field<Long> securityGetCustomEpoch() {
        SecurityGetCustomEpoch f = new SecurityGetCustomEpoch();

        return f.asField();
    }

    /**
     * Call <code>security.security_next_id</code>
     */
    public static Long securityNextId(
          Configuration configuration
    ) {
        SecurityNextId p = new SecurityNextId();

        p.execute(configuration);
        return p.getResult();
    }
}
