/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.security;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

import studio.ikara.security.jooq.DefaultCatalog;
import studio.ikara.security.jooq.security.tables.SecurityAuthorities;
import studio.ikara.security.jooq.security.tables.SecurityUserAuthorities;
import studio.ikara.security.jooq.security.tables.SecurityUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Security extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security</code>
     */
    public static final Security SECURITY = new Security();

    /**
     * The table <code>security.security_authorities</code>.
     */
    public final SecurityAuthorities SECURITY_AUTHORITIES = SecurityAuthorities.SECURITY_AUTHORITIES;

    /**
     * The table <code>security.security_user_authorities</code>.
     */
    public final SecurityUserAuthorities SECURITY_USER_AUTHORITIES = SecurityUserAuthorities.SECURITY_USER_AUTHORITIES;

    /**
     * The table <code>security.security_users</code>.
     */
    public final SecurityUsers SECURITY_USERS = SecurityUsers.SECURITY_USERS;

    /**
     * No further instances allowed
     */
    private Security() {
        super(DSL.name("security"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            SecurityAuthorities.SECURITY_AUTHORITIES,
            SecurityUserAuthorities.SECURITY_USER_AUTHORITIES,
            SecurityUsers.SECURITY_USERS
        );
    }
}
