/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.security;


import studio.ikara.security.jooq.security.tables.SecurityAuthorities;
import studio.ikara.security.jooq.security.tables.SecurityUserAuthorities;
import studio.ikara.security.jooq.security.tables.SecurityUsers;


/**
 * Convenience access to all tables in security.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>security.security_authorities</code>.
     */
    public static final SecurityAuthorities SECURITY_AUTHORITIES = SecurityAuthorities.SECURITY_AUTHORITIES;

    /**
     * The table <code>security.security_user_authorities</code>.
     */
    public static final SecurityUserAuthorities SECURITY_USER_AUTHORITIES = SecurityUserAuthorities.SECURITY_USER_AUTHORITIES;

    /**
     * The table <code>security.security_users</code>.
     */
    public static final SecurityUsers SECURITY_USERS = SecurityUsers.SECURITY_USERS;
}
