CREATE TABLE IF NOT EXISTS SECURITY_USERS
(
    ID                BIGINT                                                                  NOT NULL,
    USER_NAME         CHAR(320)                                                               NOT NULL DEFAULT 'NONE',
    EMAIL_ID          VARCHAR(320)                                                            NOT NULL DEFAULT 'NONE',
    DIAL_CODE         SMALLINT                                                                NOT NULL DEFAULT 91,
    PHONE_NUMBER      CHAR(15),
    FIRST_NAME        VARCHAR(128),
    LAST_NAME         VARCHAR(128),
    MIDDLE_NAME       VARCHAR(128),
    LOCALE_CODE       VARCHAR(10),
    PASSWORD          VARCHAR(512)                                                            NOT NULL,
    PASSWORD_HASHED   BOOLEAN                                                                          DEFAULT TRUE,
    USER_STATUS_CODE  ENUM ('ACTIVE', 'INACTIVE', 'DELETED', 'LOCKED', 'PASSWORD_EXPIRED')  NOT NULL DEFAULT 'ACTIVE',
    NO_FAILED_ATTEMPT SMALLINT                                                                         DEFAULT 0,
    CREATED_AT        DATETIME(6)                                                            NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT        DATETIME(6)                                                            NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CREATED_BY        BIGINT,
    UPDATED_BY        BIGINT,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SECURITY_USERS_USER_NAME (USER_NAME),
    UNIQUE KEY UK_SECURITY_USERS_EMAIL_ID (EMAIL_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TRIGGER UPDATE_SECURITY_USERS_TIMESTAMP
    BEFORE UPDATE
    ON SECURITY_USERS
    FOR EACH ROW
    SET NEW.UPDATED_AT = CURRENT_TIMESTAMP(6);

CREATE TABLE IF NOT EXISTS SECURITY_AUTHORITIES
(
    ID         BIGINT       NOT NULL,
    NAME       VARCHAR(50)  NOT NULL,
    CREATED_AT DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CREATED_BY BIGINT,
    UPDATED_AT DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_BY BIGINT,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SECURITY_AUTHORITIES_NAME (NAME)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TRIGGER UPDATE_SECURITY_AUTHORITIES_TIMESTAMP
    BEFORE UPDATE
    ON SECURITY_AUTHORITIES
    FOR EACH ROW
    SET NEW.UPDATED_AT = CURRENT_TIMESTAMP(6);

CREATE TABLE IF NOT EXISTS SECURITY_USER_AUTHORITIES
(
    ID           BIGINT      NOT NULL,
    USER_ID      BIGINT      NOT NULL,
    AUTHORITY_ID BIGINT      NOT NULL,
    CREATED_AT   DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CREATED_BY   BIGINT,
    UPDATED_AT   DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_BY   BIGINT,
    PRIMARY KEY (ID),
    UNIQUE KEY UK1_USER_AUTHORITIES_USER_ID_AUTHORITY_ID (USER_ID, AUTHORITY_ID),
    CONSTRAINT FK1_USER_AUTHORITIES_USER_ID_USERS_ID FOREIGN KEY (USER_ID) REFERENCES SECURITY_USERS (ID),
    CONSTRAINT FK2_USER_AUTHORITIES_AUTHORITY_ID_AUTHORITIES_ID FOREIGN KEY (AUTHORITY_ID) REFERENCES SECURITY_AUTHORITIES (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

CREATE TRIGGER UPDATE_SECURITY_USER_AUTHORITIES_TIMESTAMP
    BEFORE UPDATE
    ON SECURITY_USER_AUTHORITIES
    FOR EACH ROW
    SET NEW.UPDATED_AT = CURRENT_TIMESTAMP(6);
