security:
  db:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: Vishwas123#
    flyway:
      url: jdbc:mysql://localhost:3306

core:
  db:
    url: jdbc:mysql://localhost:3306/core
    username: root
    password: Vishwas123#
    flyway:
      url: jdbc:mysql://localhost:3306

spring:
  flyway:
    enabled: false

redis:
  url: redis://default@localhost:6379
  codec: object
  cache:
    prefix: ikara

logging:
  level:
    root: INFO
    studio.ikara: DEBUG
    org.jooq: DEBUG
    org.jooq.tools.LoggerListener: DEBUG

mq:
  host: localhost
  port: 5672
  username: ~
  password: ~
