---
spring:
  application:
    name: core
  datasource:
    url: ${core.db.url}
    username: ${core.db.username}
    password: ${core.db.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: core
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${core.db.flyway.url}
    user: ${core.db.username}
    password: ${core.db.password}
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: core
          uri: lb://core
          predicates:
            - Path=/api/core/**, /*/api/core/**, /*/*/api/core/**, /*/*/*/api/core/**, /*/*/*/*/api/core/**, /*/*/*/*/*/api/core/**, /*/*/*/*/*/*/api/core/**, /*/*/*/*/*/*/*/api/core/**, /*/*/*/*/*/*/*/*/api/core/**, /*/*/*/*/*/*/*/*/*/api/core/**
