/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.security.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import studio.ikara.security.jooq.security.tables.SecurityAuthorities;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityAuthoritiesRecord extends UpdatableRecordImpl<SecurityAuthoritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_authorities.id</code>.
     */
    public SecurityAuthoritiesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>security.security_authorities.name</code>.
     */
    public SecurityAuthoritiesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>security.security_authorities.created_at</code>.
     */
    public SecurityAuthoritiesRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>security.security_authorities.created_by</code>.
     */
    public SecurityAuthoritiesRecord setCreatedBy(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>security.security_authorities.updated_at</code>.
     */
    public SecurityAuthoritiesRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>security.security_authorities.updated_by</code>.
     */
    public SecurityAuthoritiesRecord setUpdatedBy(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAuthoritiesRecord
     */
    public SecurityAuthoritiesRecord() {
        super(SecurityAuthorities.SECURITY_AUTHORITIES);
    }

    /**
     * Create a detached, initialised SecurityAuthoritiesRecord
     */
    public SecurityAuthoritiesRecord(Long id, String name, LocalDateTime createdAt, Long createdBy, LocalDateTime updatedAt, Long updatedBy) {
        super(SecurityAuthorities.SECURITY_AUTHORITIES);

        setId(id);
        setName(name);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        resetTouchedOnNotNull();
    }
}
