/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.security.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import studio.ikara.security.jooq.security.tables.SecurityUserAuthorities;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityUserAuthoritiesRecord extends UpdatableRecordImpl<SecurityUserAuthoritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_user_authorities.id</code>.
     */
    public SecurityUserAuthoritiesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>security.security_user_authorities.user_id</code>.
     */
    public SecurityUserAuthoritiesRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>security.security_user_authorities.authority_id</code>.
     */
    public SecurityUserAuthoritiesRecord setAuthorityId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.authority_id</code>.
     */
    public Long getAuthorityId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>security.security_user_authorities.created_at</code>.
     */
    public SecurityUserAuthoritiesRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>security.security_user_authorities.created_by</code>.
     */
    public SecurityUserAuthoritiesRecord setCreatedBy(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>security.security_user_authorities.updated_at</code>.
     */
    public SecurityUserAuthoritiesRecord setUpdatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>security.security_user_authorities.updated_by</code>.
     */
    public SecurityUserAuthoritiesRecord setUpdatedBy(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityUserAuthoritiesRecord
     */
    public SecurityUserAuthoritiesRecord() {
        super(SecurityUserAuthorities.SECURITY_USER_AUTHORITIES);
    }

    /**
     * Create a detached, initialised SecurityUserAuthoritiesRecord
     */
    public SecurityUserAuthoritiesRecord(Long id, Long userId, Long authorityId, LocalDateTime createdAt, Long createdBy, LocalDateTime updatedAt, Long updatedBy) {
        super(SecurityUserAuthorities.SECURITY_USER_AUTHORITIES);

        setId(id);
        setUserId(userId);
        setAuthorityId(authorityId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        resetTouchedOnNotNull();
    }
}
