/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.public_;


import org.jooq.Catalog;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

import studio.ikara.security.jooq.DefaultCatalog;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
