/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.Keys;
import studio.ikara.security.jooq.Security;
import studio.ikara.security.jooq.tables.SecurityPermissions.SecurityPermissionsPath;
import studio.ikara.security.jooq.tables.SecurityRoles.SecurityRolesPath;
import studio.ikara.security.jooq.tables.records.SecurityRolePermissionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityRolePermissions extends TableImpl<SecurityRolePermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.security_role_permissions</code>
     */
    public static final SecurityRolePermissions SECURITY_ROLE_PERMISSIONS = new SecurityRolePermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityRolePermissionsRecord> getRecordType() {
        return SecurityRolePermissionsRecord.class;
    }

    /**
     * The column <code>security.security_role_permissions.ID</code>. Primary
     * key
     */
    public final TableField<SecurityRolePermissionsRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key");

    /**
     * The column <code>security.security_role_permissions.ROLE_ID</code>. FK to
     * security_roles
     */
    public final TableField<SecurityRolePermissionsRecord, ULong> ROLE_ID = createField(DSL.name("ROLE_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "FK to security_roles");

    /**
     * The column <code>security.security_role_permissions.PERMISSION_ID</code>.
     * FK to security_permissions
     */
    public final TableField<SecurityRolePermissionsRecord, ULong> PERMISSION_ID = createField(DSL.name("PERMISSION_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "FK to security_permissions");

    /**
     * The column <code>security.security_role_permissions.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public final TableField<SecurityRolePermissionsRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row");

    /**
     * The column <code>security.security_role_permissions.CREATED_AT</code>.
     * Time when this row is created
     */
    public final TableField<SecurityRolePermissionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created");

    /**
     * The column <code>security.security_role_permissions.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public final TableField<SecurityRolePermissionsRecord, ULong> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who updated this row");

    /**
     * The column <code>security.security_role_permissions.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public final TableField<SecurityRolePermissionsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated");

    private SecurityRolePermissions(Name alias, Table<SecurityRolePermissionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SecurityRolePermissions(Name alias, Table<SecurityRolePermissionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>security.security_role_permissions</code> table
     * reference
     */
    public SecurityRolePermissions(String alias) {
        this(DSL.name(alias), SECURITY_ROLE_PERMISSIONS);
    }

    /**
     * Create an aliased <code>security.security_role_permissions</code> table
     * reference
     */
    public SecurityRolePermissions(Name alias) {
        this(alias, SECURITY_ROLE_PERMISSIONS);
    }

    /**
     * Create a <code>security.security_role_permissions</code> table reference
     */
    public SecurityRolePermissions() {
        this(DSL.name("security_role_permissions"), null);
    }

    public <O extends Record> SecurityRolePermissions(Table<O> path, ForeignKey<O, SecurityRolePermissionsRecord> childPath, InverseForeignKey<O, SecurityRolePermissionsRecord> parentPath) {
        super(path, childPath, parentPath, SECURITY_ROLE_PERMISSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SecurityRolePermissionsPath extends SecurityRolePermissions implements Path<SecurityRolePermissionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SecurityRolePermissionsPath(Table<O> path, ForeignKey<O, SecurityRolePermissionsRecord> childPath, InverseForeignKey<O, SecurityRolePermissionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SecurityRolePermissionsPath(Name alias, Table<SecurityRolePermissionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SecurityRolePermissionsPath as(String alias) {
            return new SecurityRolePermissionsPath(DSL.name(alias), this);
        }

        @Override
        public SecurityRolePermissionsPath as(Name alias) {
            return new SecurityRolePermissionsPath(alias, this);
        }

        @Override
        public SecurityRolePermissionsPath as(Table<?> alias) {
            return new SecurityRolePermissionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public Identity<SecurityRolePermissionsRecord, ULong> getIdentity() {
        return (Identity<SecurityRolePermissionsRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<SecurityRolePermissionsRecord> getPrimaryKey() {
        return Keys.KEY_SECURITY_ROLE_PERMISSIONS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SecurityRolePermissionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SECURITY_ROLE_PERMISSIONS_UK_SECURITY_ROLE_PERMISSIONS);
    }

    @Override
    public List<ForeignKey<SecurityRolePermissionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK1_ROLE_PERMISSIONS_ROLE_ID, Keys.FK2_ROLE_PERMISSIONS_PERMISSION_ID);
    }

    private transient SecurityRolesPath _securityRoles;

    /**
     * Get the implicit join path to the <code>security.security_roles</code>
     * table.
     */
    public SecurityRolesPath securityRoles() {
        if (_securityRoles == null)
            _securityRoles = new SecurityRolesPath(this, Keys.FK1_ROLE_PERMISSIONS_ROLE_ID, null);

        return _securityRoles;
    }

    private transient SecurityPermissionsPath _securityPermissions;

    /**
     * Get the implicit join path to the
     * <code>security.security_permissions</code> table.
     */
    public SecurityPermissionsPath securityPermissions() {
        if (_securityPermissions == null)
            _securityPermissions = new SecurityPermissionsPath(this, Keys.FK2_ROLE_PERMISSIONS_PERMISSION_ID, null);

        return _securityPermissions;
    }

    @Override
    public SecurityRolePermissions as(String alias) {
        return new SecurityRolePermissions(DSL.name(alias), this);
    }

    @Override
    public SecurityRolePermissions as(Name alias) {
        return new SecurityRolePermissions(alias, this);
    }

    @Override
    public SecurityRolePermissions as(Table<?> alias) {
        return new SecurityRolePermissions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityRolePermissions rename(String name) {
        return new SecurityRolePermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityRolePermissions rename(Name name) {
        return new SecurityRolePermissions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityRolePermissions rename(Table<?> name) {
        return new SecurityRolePermissions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRolePermissions where(Condition condition) {
        return new SecurityRolePermissions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRolePermissions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRolePermissions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRolePermissions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityRolePermissions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityRolePermissions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityRolePermissions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityRolePermissions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRolePermissions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRolePermissions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
