/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import studio.ikara.security.enums.UserStatusCode;
import studio.ikara.security.jooq.Keys;
import studio.ikara.security.jooq.Security;
import studio.ikara.security.jooq.tables.SecurityAuthorities.SecurityAuthoritiesPath;
import studio.ikara.security.jooq.tables.SecurityRoles.SecurityRolesPath;
import studio.ikara.security.jooq.tables.SecurityUserAuthorities.SecurityUserAuthoritiesPath;
import studio.ikara.security.jooq.tables.SecurityUserRoles.SecurityUserRolesPath;
import studio.ikara.security.jooq.tables.records.SecurityUsersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityUsers extends TableImpl<SecurityUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.security_users</code>
     */
    public static final SecurityUsers SECURITY_USERS = new SecurityUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityUsersRecord> getRecordType() {
        return SecurityUsersRecord.class;
    }

    /**
     * The column <code>security.security_users.ID</code>. Primary key
     */
    public final TableField<SecurityUsersRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key");

    /**
     * The column <code>security.security_users.USER_NAME</code>. Unique login
     * username; NONE when not set
     */
    public final TableField<SecurityUsersRecord, String> USER_NAME = createField(DSL.name("USER_NAME"), SQLDataType.VARCHAR(320).nullable(false).defaultValue(DSL.inline("NONE", SQLDataType.VARCHAR)), this, "Unique login username; NONE when not set");

    /**
     * The column <code>security.security_users.EMAIL</code>. Email related to
     * this owner.
     */
    public final TableField<SecurityUsersRecord, String> EMAIL = createField(DSL.name("EMAIL"), SQLDataType.VARCHAR(512), this, "Email related to this owner.");

    /**
     * The column <code>security.security_users.DIAL_CODE</code>. Dial code of
     * the phone number this owner has.
     */
    public final TableField<SecurityUsersRecord, Short> DIAL_CODE = createField(DSL.name("DIAL_CODE"), SQLDataType.SMALLINT.defaultValue(DSL.inline("91", SQLDataType.SMALLINT)), this, "Dial code of the phone number this owner has.");

    /**
     * The column <code>security.security_users.PHONE_NUMBER</code>. Phone
     * number related to this owner.
     */
    public final TableField<SecurityUsersRecord, String> PHONE_NUMBER = createField(DSL.name("PHONE_NUMBER"), SQLDataType.CHAR(15), this, "Phone number related to this owner.");

    /**
     * The column <code>security.security_users.FIRST_NAME</code>. First name
     */
    public final TableField<SecurityUsersRecord, String> FIRST_NAME = createField(DSL.name("FIRST_NAME"), SQLDataType.VARCHAR(128), this, "First name");

    /**
     * The column <code>security.security_users.LAST_NAME</code>. Last name
     */
    public final TableField<SecurityUsersRecord, String> LAST_NAME = createField(DSL.name("LAST_NAME"), SQLDataType.VARCHAR(128), this, "Last name");

    /**
     * The column <code>security.security_users.MIDDLE_NAME</code>. Middle name
     */
    public final TableField<SecurityUsersRecord, String> MIDDLE_NAME = createField(DSL.name("MIDDLE_NAME"), SQLDataType.VARCHAR(128), this, "Middle name");

    /**
     * The column <code>security.security_users.LOCALE_CODE</code>. Locale code
     * e.g. en_US
     */
    public final TableField<SecurityUsersRecord, String> LOCALE_CODE = createField(DSL.name("LOCALE_CODE"), SQLDataType.VARCHAR(10), this, "Locale code e.g. en_US");

    /**
     * The column <code>security.security_users.PASSWORD</code>. BCrypt-hashed
     * password
     */
    public final TableField<SecurityUsersRecord, String> PASSWORD = createField(DSL.name("PASSWORD"), SQLDataType.VARCHAR(512).nullable(false), this, "BCrypt-hashed password");

    /**
     * The column <code>security.security_users.PASSWORD_HASHED</code>. TRUE if
     * password is BCrypt-hashed
     */
    public final TableField<SecurityUsersRecord, Byte> PASSWORD_HASHED = createField(DSL.name("PASSWORD_HASHED"), SQLDataType.TINYINT.defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "TRUE if password is BCrypt-hashed");

    /**
     * The column <code>security.security_users.USER_STATUS_CODE</code>. Current
     * account status
     */
    public final TableField<SecurityUsersRecord, UserStatusCode> USER_STATUS_CODE = createField(DSL.name("USER_STATUS_CODE"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.inline("ACTIVE", SQLDataType.VARCHAR)), this, "Current account status", new EnumConverter<String, UserStatusCode>(String.class, UserStatusCode.class));

    /**
     * The column <code>security.security_users.NO_FAILED_ATTEMPT</code>.
     * Consecutive failed login attempts
     */
    public final TableField<SecurityUsersRecord, Short> NO_FAILED_ATTEMPT = createField(DSL.name("NO_FAILED_ATTEMPT"), SQLDataType.SMALLINT.defaultValue(DSL.inline("0", SQLDataType.SMALLINT)), this, "Consecutive failed login attempts");

    /**
     * The column <code>security.security_users.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public final TableField<SecurityUsersRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row");

    /**
     * The column <code>security.security_users.CREATED_AT</code>. Time when
     * this row is created
     */
    public final TableField<SecurityUsersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created");

    /**
     * The column <code>security.security_users.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public final TableField<SecurityUsersRecord, ULong> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who updated this row");

    /**
     * The column <code>security.security_users.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public final TableField<SecurityUsersRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated");

    private SecurityUsers(Name alias, Table<SecurityUsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SecurityUsers(Name alias, Table<SecurityUsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>security.security_users</code> table reference
     */
    public SecurityUsers(String alias) {
        this(DSL.name(alias), SECURITY_USERS);
    }

    /**
     * Create an aliased <code>security.security_users</code> table reference
     */
    public SecurityUsers(Name alias) {
        this(alias, SECURITY_USERS);
    }

    /**
     * Create a <code>security.security_users</code> table reference
     */
    public SecurityUsers() {
        this(DSL.name("security_users"), null);
    }

    public <O extends Record> SecurityUsers(Table<O> path, ForeignKey<O, SecurityUsersRecord> childPath, InverseForeignKey<O, SecurityUsersRecord> parentPath) {
        super(path, childPath, parentPath, SECURITY_USERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SecurityUsersPath extends SecurityUsers implements Path<SecurityUsersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SecurityUsersPath(Table<O> path, ForeignKey<O, SecurityUsersRecord> childPath, InverseForeignKey<O, SecurityUsersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SecurityUsersPath(Name alias, Table<SecurityUsersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SecurityUsersPath as(String alias) {
            return new SecurityUsersPath(DSL.name(alias), this);
        }

        @Override
        public SecurityUsersPath as(Name alias) {
            return new SecurityUsersPath(alias, this);
        }

        @Override
        public SecurityUsersPath as(Table<?> alias) {
            return new SecurityUsersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public Identity<SecurityUsersRecord, ULong> getIdentity() {
        return (Identity<SecurityUsersRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<SecurityUsersRecord> getPrimaryKey() {
        return Keys.KEY_SECURITY_USERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SecurityUsersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SECURITY_USERS_UK_SECURITY_USERS_EMAIL, Keys.KEY_SECURITY_USERS_UK_SECURITY_USERS_USER_NAME);
    }

    private transient SecurityUserAuthoritiesPath _securityUserAuthorities;

    /**
     * Get the implicit to-many join path to the
     * <code>security.security_user_authorities</code> table
     */
    public SecurityUserAuthoritiesPath securityUserAuthorities() {
        if (_securityUserAuthorities == null)
            _securityUserAuthorities = new SecurityUserAuthoritiesPath(this, null, Keys.FK1_USER_AUTHORITIES_USER_ID_USERS_ID.getInverseKey());

        return _securityUserAuthorities;
    }

    private transient SecurityUserRolesPath _securityUserRoles;

    /**
     * Get the implicit to-many join path to the
     * <code>security.security_user_roles</code> table
     */
    public SecurityUserRolesPath securityUserRoles() {
        if (_securityUserRoles == null)
            _securityUserRoles = new SecurityUserRolesPath(this, null, Keys.FK1_USER_ROLES_USER_ID.getInverseKey());

        return _securityUserRoles;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>security.security_authorities</code> table
     */
    public SecurityAuthoritiesPath securityAuthorities() {
        return securityUserAuthorities().securityAuthorities();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>security.security_roles</code> table
     */
    public SecurityRolesPath securityRoles() {
        return securityUserRoles().securityRoles();
    }

    @Override
    public SecurityUsers as(String alias) {
        return new SecurityUsers(DSL.name(alias), this);
    }

    @Override
    public SecurityUsers as(Name alias) {
        return new SecurityUsers(alias, this);
    }

    @Override
    public SecurityUsers as(Table<?> alias) {
        return new SecurityUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUsers rename(String name) {
        return new SecurityUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUsers rename(Name name) {
        return new SecurityUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUsers rename(Table<?> name) {
        return new SecurityUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUsers where(Condition condition) {
        return new SecurityUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
