/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.Keys;
import studio.ikara.security.jooq.Security;
import studio.ikara.security.jooq.tables.SecurityRoles.SecurityRolesPath;
import studio.ikara.security.jooq.tables.SecurityUsers.SecurityUsersPath;
import studio.ikara.security.jooq.tables.records.SecurityUserRolesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityUserRoles extends TableImpl<SecurityUserRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.security_user_roles</code>
     */
    public static final SecurityUserRoles SECURITY_USER_ROLES = new SecurityUserRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityUserRolesRecord> getRecordType() {
        return SecurityUserRolesRecord.class;
    }

    /**
     * The column <code>security.security_user_roles.ID</code>. Primary key
     */
    public final TableField<SecurityUserRolesRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key");

    /**
     * The column <code>security.security_user_roles.USER_ID</code>. FK to
     * security_users
     */
    public final TableField<SecurityUserRolesRecord, ULong> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "FK to security_users");

    /**
     * The column <code>security.security_user_roles.ROLE_ID</code>. FK to
     * security_roles
     */
    public final TableField<SecurityUserRolesRecord, ULong> ROLE_ID = createField(DSL.name("ROLE_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "FK to security_roles");

    /**
     * The column <code>security.security_user_roles.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public final TableField<SecurityUserRolesRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row");

    /**
     * The column <code>security.security_user_roles.CREATED_AT</code>. Time
     * when this row is created
     */
    public final TableField<SecurityUserRolesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created");

    /**
     * The column <code>security.security_user_roles.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public final TableField<SecurityUserRolesRecord, ULong> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who updated this row");

    /**
     * The column <code>security.security_user_roles.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public final TableField<SecurityUserRolesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated");

    private SecurityUserRoles(Name alias, Table<SecurityUserRolesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SecurityUserRoles(Name alias, Table<SecurityUserRolesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>security.security_user_roles</code> table
     * reference
     */
    public SecurityUserRoles(String alias) {
        this(DSL.name(alias), SECURITY_USER_ROLES);
    }

    /**
     * Create an aliased <code>security.security_user_roles</code> table
     * reference
     */
    public SecurityUserRoles(Name alias) {
        this(alias, SECURITY_USER_ROLES);
    }

    /**
     * Create a <code>security.security_user_roles</code> table reference
     */
    public SecurityUserRoles() {
        this(DSL.name("security_user_roles"), null);
    }

    public <O extends Record> SecurityUserRoles(Table<O> path, ForeignKey<O, SecurityUserRolesRecord> childPath, InverseForeignKey<O, SecurityUserRolesRecord> parentPath) {
        super(path, childPath, parentPath, SECURITY_USER_ROLES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SecurityUserRolesPath extends SecurityUserRoles implements Path<SecurityUserRolesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SecurityUserRolesPath(Table<O> path, ForeignKey<O, SecurityUserRolesRecord> childPath, InverseForeignKey<O, SecurityUserRolesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SecurityUserRolesPath(Name alias, Table<SecurityUserRolesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SecurityUserRolesPath as(String alias) {
            return new SecurityUserRolesPath(DSL.name(alias), this);
        }

        @Override
        public SecurityUserRolesPath as(Name alias) {
            return new SecurityUserRolesPath(alias, this);
        }

        @Override
        public SecurityUserRolesPath as(Table<?> alias) {
            return new SecurityUserRolesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public Identity<SecurityUserRolesRecord, ULong> getIdentity() {
        return (Identity<SecurityUserRolesRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<SecurityUserRolesRecord> getPrimaryKey() {
        return Keys.KEY_SECURITY_USER_ROLES_PRIMARY;
    }

    @Override
    public List<UniqueKey<SecurityUserRolesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SECURITY_USER_ROLES_UK_SECURITY_USER_ROLES);
    }

    @Override
    public List<ForeignKey<SecurityUserRolesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK1_USER_ROLES_USER_ID, Keys.FK2_USER_ROLES_ROLE_ID);
    }

    private transient SecurityUsersPath _securityUsers;

    /**
     * Get the implicit join path to the <code>security.security_users</code>
     * table.
     */
    public SecurityUsersPath securityUsers() {
        if (_securityUsers == null)
            _securityUsers = new SecurityUsersPath(this, Keys.FK1_USER_ROLES_USER_ID, null);

        return _securityUsers;
    }

    private transient SecurityRolesPath _securityRoles;

    /**
     * Get the implicit join path to the <code>security.security_roles</code>
     * table.
     */
    public SecurityRolesPath securityRoles() {
        if (_securityRoles == null)
            _securityRoles = new SecurityRolesPath(this, Keys.FK2_USER_ROLES_ROLE_ID, null);

        return _securityRoles;
    }

    @Override
    public SecurityUserRoles as(String alias) {
        return new SecurityUserRoles(DSL.name(alias), this);
    }

    @Override
    public SecurityUserRoles as(Name alias) {
        return new SecurityUserRoles(alias, this);
    }

    @Override
    public SecurityUserRoles as(Table<?> alias) {
        return new SecurityUserRoles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUserRoles rename(String name) {
        return new SecurityUserRoles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUserRoles rename(Name name) {
        return new SecurityUserRoles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUserRoles rename(Table<?> name) {
        return new SecurityUserRoles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserRoles where(Condition condition) {
        return new SecurityUserRoles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserRoles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserRoles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserRoles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUserRoles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUserRoles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUserRoles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUserRoles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserRoles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserRoles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
