/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.Keys;
import studio.ikara.security.jooq.Security;
import studio.ikara.security.jooq.tables.SecurityPermissions.SecurityPermissionsPath;
import studio.ikara.security.jooq.tables.SecurityRolePermissions.SecurityRolePermissionsPath;
import studio.ikara.security.jooq.tables.SecurityUserRoles.SecurityUserRolesPath;
import studio.ikara.security.jooq.tables.SecurityUsers.SecurityUsersPath;
import studio.ikara.security.jooq.tables.records.SecurityRolesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityRoles extends TableImpl<SecurityRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.security_roles</code>
     */
    public static final SecurityRoles SECURITY_ROLES = new SecurityRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityRolesRecord> getRecordType() {
        return SecurityRolesRecord.class;
    }

    /**
     * The column <code>security.security_roles.ID</code>. Primary key
     */
    public final TableField<SecurityRolesRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key");

    /**
     * The column <code>security.security_roles.NAME</code>. Role name e.g.
     * ADMIN
     */
    public final TableField<SecurityRolesRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "Role name e.g. ADMIN");

    /**
     * The column <code>security.security_roles.DESCRIPTION</code>.
     * Human-readable description
     */
    public final TableField<SecurityRolesRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(255), this, "Human-readable description");

    /**
     * The column <code>security.security_roles.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public final TableField<SecurityRolesRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row");

    /**
     * The column <code>security.security_roles.CREATED_AT</code>. Time when
     * this row is created
     */
    public final TableField<SecurityRolesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created");

    /**
     * The column <code>security.security_roles.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public final TableField<SecurityRolesRecord, ULong> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who updated this row");

    /**
     * The column <code>security.security_roles.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public final TableField<SecurityRolesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated");

    private SecurityRoles(Name alias, Table<SecurityRolesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SecurityRoles(Name alias, Table<SecurityRolesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>security.security_roles</code> table reference
     */
    public SecurityRoles(String alias) {
        this(DSL.name(alias), SECURITY_ROLES);
    }

    /**
     * Create an aliased <code>security.security_roles</code> table reference
     */
    public SecurityRoles(Name alias) {
        this(alias, SECURITY_ROLES);
    }

    /**
     * Create a <code>security.security_roles</code> table reference
     */
    public SecurityRoles() {
        this(DSL.name("security_roles"), null);
    }

    public <O extends Record> SecurityRoles(Table<O> path, ForeignKey<O, SecurityRolesRecord> childPath, InverseForeignKey<O, SecurityRolesRecord> parentPath) {
        super(path, childPath, parentPath, SECURITY_ROLES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SecurityRolesPath extends SecurityRoles implements Path<SecurityRolesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SecurityRolesPath(Table<O> path, ForeignKey<O, SecurityRolesRecord> childPath, InverseForeignKey<O, SecurityRolesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SecurityRolesPath(Name alias, Table<SecurityRolesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SecurityRolesPath as(String alias) {
            return new SecurityRolesPath(DSL.name(alias), this);
        }

        @Override
        public SecurityRolesPath as(Name alias) {
            return new SecurityRolesPath(alias, this);
        }

        @Override
        public SecurityRolesPath as(Table<?> alias) {
            return new SecurityRolesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public Identity<SecurityRolesRecord, ULong> getIdentity() {
        return (Identity<SecurityRolesRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<SecurityRolesRecord> getPrimaryKey() {
        return Keys.KEY_SECURITY_ROLES_PRIMARY;
    }

    @Override
    public List<UniqueKey<SecurityRolesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SECURITY_ROLES_UK_SECURITY_ROLES_NAME);
    }

    private transient SecurityRolePermissionsPath _securityRolePermissions;

    /**
     * Get the implicit to-many join path to the
     * <code>security.security_role_permissions</code> table
     */
    public SecurityRolePermissionsPath securityRolePermissions() {
        if (_securityRolePermissions == null)
            _securityRolePermissions = new SecurityRolePermissionsPath(this, null, Keys.FK1_ROLE_PERMISSIONS_ROLE_ID.getInverseKey());

        return _securityRolePermissions;
    }

    private transient SecurityUserRolesPath _securityUserRoles;

    /**
     * Get the implicit to-many join path to the
     * <code>security.security_user_roles</code> table
     */
    public SecurityUserRolesPath securityUserRoles() {
        if (_securityUserRoles == null)
            _securityUserRoles = new SecurityUserRolesPath(this, null, Keys.FK2_USER_ROLES_ROLE_ID.getInverseKey());

        return _securityUserRoles;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>security.security_permissions</code> table
     */
    public SecurityPermissionsPath securityPermissions() {
        return securityRolePermissions().securityPermissions();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>security.security_users</code> table
     */
    public SecurityUsersPath securityUsers() {
        return securityUserRoles().securityUsers();
    }

    @Override
    public SecurityRoles as(String alias) {
        return new SecurityRoles(DSL.name(alias), this);
    }

    @Override
    public SecurityRoles as(Name alias) {
        return new SecurityRoles(alias, this);
    }

    @Override
    public SecurityRoles as(Table<?> alias) {
        return new SecurityRoles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityRoles rename(String name) {
        return new SecurityRoles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityRoles rename(Name name) {
        return new SecurityRoles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityRoles rename(Table<?> name) {
        return new SecurityRoles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRoles where(Condition condition) {
        return new SecurityRoles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRoles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRoles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRoles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityRoles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityRoles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityRoles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityRoles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRoles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityRoles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
