/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.Keys;
import studio.ikara.security.jooq.Security;
import studio.ikara.security.jooq.tables.SecurityRolePermissions.SecurityRolePermissionsPath;
import studio.ikara.security.jooq.tables.SecurityRoles.SecurityRolesPath;
import studio.ikara.security.jooq.tables.records.SecurityPermissionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityPermissions extends TableImpl<SecurityPermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.security_permissions</code>
     */
    public static final SecurityPermissions SECURITY_PERMISSIONS = new SecurityPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityPermissionsRecord> getRecordType() {
        return SecurityPermissionsRecord.class;
    }

    /**
     * The column <code>security.security_permissions.ID</code>. Primary key
     */
    public final TableField<SecurityPermissionsRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key");

    /**
     * The column <code>security.security_permissions.CODE</code>. Permission
     * code e.g. Application_CREATE
     */
    public final TableField<SecurityPermissionsRecord, String> CODE = createField(DSL.name("CODE"), SQLDataType.VARCHAR(100).nullable(false), this, "Permission code e.g. Application_CREATE");

    /**
     * The column <code>security.security_permissions.DESCRIPTION</code>.
     * Human-readable description
     */
    public final TableField<SecurityPermissionsRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(255), this, "Human-readable description");

    /**
     * The column <code>security.security_permissions.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public final TableField<SecurityPermissionsRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row");

    /**
     * The column <code>security.security_permissions.CREATED_AT</code>. Time
     * when this row is created
     */
    public final TableField<SecurityPermissionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created");

    /**
     * The column <code>security.security_permissions.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public final TableField<SecurityPermissionsRecord, ULong> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who updated this row");

    /**
     * The column <code>security.security_permissions.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public final TableField<SecurityPermissionsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated");

    private SecurityPermissions(Name alias, Table<SecurityPermissionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SecurityPermissions(Name alias, Table<SecurityPermissionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>security.security_permissions</code> table
     * reference
     */
    public SecurityPermissions(String alias) {
        this(DSL.name(alias), SECURITY_PERMISSIONS);
    }

    /**
     * Create an aliased <code>security.security_permissions</code> table
     * reference
     */
    public SecurityPermissions(Name alias) {
        this(alias, SECURITY_PERMISSIONS);
    }

    /**
     * Create a <code>security.security_permissions</code> table reference
     */
    public SecurityPermissions() {
        this(DSL.name("security_permissions"), null);
    }

    public <O extends Record> SecurityPermissions(Table<O> path, ForeignKey<O, SecurityPermissionsRecord> childPath, InverseForeignKey<O, SecurityPermissionsRecord> parentPath) {
        super(path, childPath, parentPath, SECURITY_PERMISSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SecurityPermissionsPath extends SecurityPermissions implements Path<SecurityPermissionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SecurityPermissionsPath(Table<O> path, ForeignKey<O, SecurityPermissionsRecord> childPath, InverseForeignKey<O, SecurityPermissionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SecurityPermissionsPath(Name alias, Table<SecurityPermissionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SecurityPermissionsPath as(String alias) {
            return new SecurityPermissionsPath(DSL.name(alias), this);
        }

        @Override
        public SecurityPermissionsPath as(Name alias) {
            return new SecurityPermissionsPath(alias, this);
        }

        @Override
        public SecurityPermissionsPath as(Table<?> alias) {
            return new SecurityPermissionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public Identity<SecurityPermissionsRecord, ULong> getIdentity() {
        return (Identity<SecurityPermissionsRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<SecurityPermissionsRecord> getPrimaryKey() {
        return Keys.KEY_SECURITY_PERMISSIONS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SecurityPermissionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SECURITY_PERMISSIONS_UK_SECURITY_PERMISSIONS_CODE);
    }

    private transient SecurityRolePermissionsPath _securityRolePermissions;

    /**
     * Get the implicit to-many join path to the
     * <code>security.security_role_permissions</code> table
     */
    public SecurityRolePermissionsPath securityRolePermissions() {
        if (_securityRolePermissions == null)
            _securityRolePermissions = new SecurityRolePermissionsPath(this, null, Keys.FK2_ROLE_PERMISSIONS_PERMISSION_ID.getInverseKey());

        return _securityRolePermissions;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>security.security_roles</code> table
     */
    public SecurityRolesPath securityRoles() {
        return securityRolePermissions().securityRoles();
    }

    @Override
    public SecurityPermissions as(String alias) {
        return new SecurityPermissions(DSL.name(alias), this);
    }

    @Override
    public SecurityPermissions as(Name alias) {
        return new SecurityPermissions(alias, this);
    }

    @Override
    public SecurityPermissions as(Table<?> alias) {
        return new SecurityPermissions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityPermissions rename(String name) {
        return new SecurityPermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityPermissions rename(Name name) {
        return new SecurityPermissions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityPermissions rename(Table<?> name) {
        return new SecurityPermissions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityPermissions where(Condition condition) {
        return new SecurityPermissions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityPermissions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityPermissions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityPermissions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityPermissions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityPermissions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityPermissions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityPermissions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityPermissions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityPermissions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
