/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.Keys;
import studio.ikara.security.jooq.Security;
import studio.ikara.security.jooq.tables.SecurityAuthorities.SecurityAuthoritiesPath;
import studio.ikara.security.jooq.tables.SecurityUsers.SecurityUsersPath;
import studio.ikara.security.jooq.tables.records.SecurityUserAuthoritiesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityUserAuthorities extends TableImpl<SecurityUserAuthoritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.security_user_authorities</code>
     */
    public static final SecurityUserAuthorities SECURITY_USER_AUTHORITIES = new SecurityUserAuthorities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityUserAuthoritiesRecord> getRecordType() {
        return SecurityUserAuthoritiesRecord.class;
    }

    /**
     * The column <code>security.security_user_authorities.ID</code>. Primary
     * key
     */
    public final TableField<SecurityUserAuthoritiesRecord, ULong> ID = createField(DSL.name("ID"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "Primary key");

    /**
     * The column <code>security.security_user_authorities.USER_ID</code>. FK to
     * security_users
     */
    public final TableField<SecurityUserAuthoritiesRecord, ULong> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "FK to security_users");

    /**
     * The column <code>security.security_user_authorities.AUTHORITY_ID</code>.
     * FK to security_authorities
     */
    public final TableField<SecurityUserAuthoritiesRecord, ULong> AUTHORITY_ID = createField(DSL.name("AUTHORITY_ID"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "FK to security_authorities");

    /**
     * The column <code>security.security_user_authorities.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public final TableField<SecurityUserAuthoritiesRecord, ULong> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who created this row");

    /**
     * The column <code>security.security_user_authorities.CREATED_AT</code>.
     * Time when this row is created
     */
    public final TableField<SecurityUserAuthoritiesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is created");

    /**
     * The column <code>security.security_user_authorities.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public final TableField<SecurityUserAuthoritiesRecord, ULong> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINTUNSIGNED, this, "ID of the user who updated this row");

    /**
     * The column <code>security.security_user_authorities.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public final TableField<SecurityUserAuthoritiesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "Time when this row is updated");

    private SecurityUserAuthorities(Name alias, Table<SecurityUserAuthoritiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SecurityUserAuthorities(Name alias, Table<SecurityUserAuthoritiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>security.security_user_authorities</code> table
     * reference
     */
    public SecurityUserAuthorities(String alias) {
        this(DSL.name(alias), SECURITY_USER_AUTHORITIES);
    }

    /**
     * Create an aliased <code>security.security_user_authorities</code> table
     * reference
     */
    public SecurityUserAuthorities(Name alias) {
        this(alias, SECURITY_USER_AUTHORITIES);
    }

    /**
     * Create a <code>security.security_user_authorities</code> table reference
     */
    public SecurityUserAuthorities() {
        this(DSL.name("security_user_authorities"), null);
    }

    public <O extends Record> SecurityUserAuthorities(Table<O> path, ForeignKey<O, SecurityUserAuthoritiesRecord> childPath, InverseForeignKey<O, SecurityUserAuthoritiesRecord> parentPath) {
        super(path, childPath, parentPath, SECURITY_USER_AUTHORITIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SecurityUserAuthoritiesPath extends SecurityUserAuthorities implements Path<SecurityUserAuthoritiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SecurityUserAuthoritiesPath(Table<O> path, ForeignKey<O, SecurityUserAuthoritiesRecord> childPath, InverseForeignKey<O, SecurityUserAuthoritiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SecurityUserAuthoritiesPath(Name alias, Table<SecurityUserAuthoritiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SecurityUserAuthoritiesPath as(String alias) {
            return new SecurityUserAuthoritiesPath(DSL.name(alias), this);
        }

        @Override
        public SecurityUserAuthoritiesPath as(Name alias) {
            return new SecurityUserAuthoritiesPath(alias, this);
        }

        @Override
        public SecurityUserAuthoritiesPath as(Table<?> alias) {
            return new SecurityUserAuthoritiesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public Identity<SecurityUserAuthoritiesRecord, ULong> getIdentity() {
        return (Identity<SecurityUserAuthoritiesRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<SecurityUserAuthoritiesRecord> getPrimaryKey() {
        return Keys.KEY_SECURITY_USER_AUTHORITIES_PRIMARY;
    }

    @Override
    public List<UniqueKey<SecurityUserAuthoritiesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SECURITY_USER_AUTHORITIES_UK1_USER_AUTHORITIES_USER_ID_AUTHORITY_ID);
    }

    @Override
    public List<ForeignKey<SecurityUserAuthoritiesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK1_USER_AUTHORITIES_USER_ID_USERS_ID, Keys.FK2_USER_AUTHORITIES_AUTHORITY_ID_AUTHORITIES_ID);
    }

    private transient SecurityUsersPath _securityUsers;

    /**
     * Get the implicit join path to the <code>security.security_users</code>
     * table.
     */
    public SecurityUsersPath securityUsers() {
        if (_securityUsers == null)
            _securityUsers = new SecurityUsersPath(this, Keys.FK1_USER_AUTHORITIES_USER_ID_USERS_ID, null);

        return _securityUsers;
    }

    private transient SecurityAuthoritiesPath _securityAuthorities;

    /**
     * Get the implicit join path to the
     * <code>security.security_authorities</code> table.
     */
    public SecurityAuthoritiesPath securityAuthorities() {
        if (_securityAuthorities == null)
            _securityAuthorities = new SecurityAuthoritiesPath(this, Keys.FK2_USER_AUTHORITIES_AUTHORITY_ID_AUTHORITIES_ID, null);

        return _securityAuthorities;
    }

    @Override
    public SecurityUserAuthorities as(String alias) {
        return new SecurityUserAuthorities(DSL.name(alias), this);
    }

    @Override
    public SecurityUserAuthorities as(Name alias) {
        return new SecurityUserAuthorities(alias, this);
    }

    @Override
    public SecurityUserAuthorities as(Table<?> alias) {
        return new SecurityUserAuthorities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUserAuthorities rename(String name) {
        return new SecurityUserAuthorities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUserAuthorities rename(Name name) {
        return new SecurityUserAuthorities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityUserAuthorities rename(Table<?> name) {
        return new SecurityUserAuthorities(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserAuthorities where(Condition condition) {
        return new SecurityUserAuthorities(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserAuthorities where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserAuthorities where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserAuthorities where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUserAuthorities where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUserAuthorities where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUserAuthorities where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SecurityUserAuthorities where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserAuthorities whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SecurityUserAuthorities whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
