/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import studio.ikara.security.enums.UserStatusCode;
import studio.ikara.security.jooq.tables.SecurityUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityUsersRecord extends UpdatableRecordImpl<SecurityUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_users.ID</code>. Primary key
     */
    public SecurityUsersRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_users.USER_NAME</code>. Unique login
     * username; NONE when not set
     */
    public SecurityUsersRecord setUserName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.USER_NAME</code>. Unique login
     * username; NONE when not set
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>security.security_users.EMAIL</code>. Email related to
     * this owner.
     */
    public SecurityUsersRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.EMAIL</code>. Email related to
     * this owner.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>security.security_users.DIAL_CODE</code>. Dial code of
     * the phone number this owner has.
     */
    public SecurityUsersRecord setDialCode(Short value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.DIAL_CODE</code>. Dial code of
     * the phone number this owner has.
     */
    public Short getDialCode() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>security.security_users.PHONE_NUMBER</code>. Phone
     * number related to this owner.
     */
    public SecurityUsersRecord setPhoneNumber(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.PHONE_NUMBER</code>. Phone
     * number related to this owner.
     */
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>security.security_users.FIRST_NAME</code>. First name
     */
    public SecurityUsersRecord setFirstName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.FIRST_NAME</code>. First name
     */
    public String getFirstName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>security.security_users.LAST_NAME</code>. Last name
     */
    public SecurityUsersRecord setLastName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.LAST_NAME</code>. Last name
     */
    public String getLastName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>security.security_users.MIDDLE_NAME</code>. Middle name
     */
    public SecurityUsersRecord setMiddleName(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.MIDDLE_NAME</code>. Middle name
     */
    public String getMiddleName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>security.security_users.LOCALE_CODE</code>. Locale code
     * e.g. en_US
     */
    public SecurityUsersRecord setLocaleCode(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.LOCALE_CODE</code>. Locale code
     * e.g. en_US
     */
    public String getLocaleCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>security.security_users.PASSWORD</code>. BCrypt-hashed
     * password
     */
    public SecurityUsersRecord setPassword(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.PASSWORD</code>. BCrypt-hashed
     * password
     */
    public String getPassword() {
        return (String) get(9);
    }

    /**
     * Setter for <code>security.security_users.PASSWORD_HASHED</code>. TRUE if
     * password is BCrypt-hashed
     */
    public SecurityUsersRecord setPasswordHashed(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.PASSWORD_HASHED</code>. TRUE if
     * password is BCrypt-hashed
     */
    public Byte getPasswordHashed() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>security.security_users.USER_STATUS_CODE</code>. Current
     * account status
     */
    public SecurityUsersRecord setUserStatusCode(UserStatusCode value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.USER_STATUS_CODE</code>. Current
     * account status
     */
    public UserStatusCode getUserStatusCode() {
        return (UserStatusCode) get(11);
    }

    /**
     * Setter for <code>security.security_users.NO_FAILED_ATTEMPT</code>.
     * Consecutive failed login attempts
     */
    public SecurityUsersRecord setNoFailedAttempt(Short value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.NO_FAILED_ATTEMPT</code>.
     * Consecutive failed login attempts
     */
    public Short getNoFailedAttempt() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>security.security_users.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public SecurityUsersRecord setCreatedBy(ULong value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(13);
    }

    /**
     * Setter for <code>security.security_users.CREATED_AT</code>. Time when
     * this row is created
     */
    public SecurityUsersRecord setCreatedAt(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.CREATED_AT</code>. Time when
     * this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>security.security_users.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public SecurityUsersRecord setUpdatedBy(ULong value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(15);
    }

    /**
     * Setter for <code>security.security_users.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public SecurityUsersRecord setUpdatedAt(LocalDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>security.security_users.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityUsersRecord
     */
    public SecurityUsersRecord() {
        super(SecurityUsers.SECURITY_USERS);
    }

    /**
     * Create a detached, initialised SecurityUsersRecord
     */
    public SecurityUsersRecord(ULong id, String userName, String email, Short dialCode, String phoneNumber, String firstName, String lastName, String middleName, String localeCode, String password, Byte passwordHashed, UserStatusCode userStatusCode, Short noFailedAttempt, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityUsers.SECURITY_USERS);

        setId(id);
        setUserName(userName);
        setEmail(email);
        setDialCode(dialCode);
        setPhoneNumber(phoneNumber);
        setFirstName(firstName);
        setLastName(lastName);
        setMiddleName(middleName);
        setLocaleCode(localeCode);
        setPassword(password);
        setPasswordHashed(passwordHashed);
        setUserStatusCode(userStatusCode);
        setNoFailedAttempt(noFailedAttempt);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
