/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.tables.SecurityRolePermissions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityRolePermissionsRecord extends UpdatableRecordImpl<SecurityRolePermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_role_permissions.ID</code>. Primary
     * key
     */
    public SecurityRolePermissionsRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_role_permissions.ID</code>. Primary
     * key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_role_permissions.ROLE_ID</code>. FK to
     * security_roles
     */
    public SecurityRolePermissionsRecord setRoleId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_role_permissions.ROLE_ID</code>. FK to
     * security_roles
     */
    public ULong getRoleId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_role_permissions.PERMISSION_ID</code>.
     * FK to security_permissions
     */
    public SecurityRolePermissionsRecord setPermissionId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_role_permissions.PERMISSION_ID</code>.
     * FK to security_permissions
     */
    public ULong getPermissionId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>security.security_role_permissions.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public SecurityRolePermissionsRecord setCreatedBy(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_role_permissions.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>security.security_role_permissions.CREATED_AT</code>.
     * Time when this row is created
     */
    public SecurityRolePermissionsRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_role_permissions.CREATED_AT</code>.
     * Time when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>security.security_role_permissions.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public SecurityRolePermissionsRecord setUpdatedBy(ULong value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_role_permissions.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>security.security_role_permissions.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public SecurityRolePermissionsRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_role_permissions.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityRolePermissionsRecord
     */
    public SecurityRolePermissionsRecord() {
        super(SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS);
    }

    /**
     * Create a detached, initialised SecurityRolePermissionsRecord
     */
    public SecurityRolePermissionsRecord(ULong id, ULong roleId, ULong permissionId, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS);

        setId(id);
        setRoleId(roleId);
        setPermissionId(permissionId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
