/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.tables.SecurityUserAuthorities;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityUserAuthoritiesRecord extends UpdatableRecordImpl<SecurityUserAuthoritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_user_authorities.ID</code>. Primary
     * key
     */
    public SecurityUserAuthoritiesRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.ID</code>. Primary
     * key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_user_authorities.USER_ID</code>. FK to
     * security_users
     */
    public SecurityUserAuthoritiesRecord setUserId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.USER_ID</code>. FK to
     * security_users
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_user_authorities.AUTHORITY_ID</code>.
     * FK to security_authorities
     */
    public SecurityUserAuthoritiesRecord setAuthorityId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.AUTHORITY_ID</code>.
     * FK to security_authorities
     */
    public ULong getAuthorityId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>security.security_user_authorities.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public SecurityUserAuthoritiesRecord setCreatedBy(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.CREATED_BY</code>. ID
     * of the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>security.security_user_authorities.CREATED_AT</code>.
     * Time when this row is created
     */
    public SecurityUserAuthoritiesRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.CREATED_AT</code>.
     * Time when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>security.security_user_authorities.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public SecurityUserAuthoritiesRecord setUpdatedBy(ULong value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.UPDATED_BY</code>. ID
     * of the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>security.security_user_authorities.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public SecurityUserAuthoritiesRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_authorities.UPDATED_AT</code>.
     * Time when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityUserAuthoritiesRecord
     */
    public SecurityUserAuthoritiesRecord() {
        super(SecurityUserAuthorities.SECURITY_USER_AUTHORITIES);
    }

    /**
     * Create a detached, initialised SecurityUserAuthoritiesRecord
     */
    public SecurityUserAuthoritiesRecord(ULong id, ULong userId, ULong authorityId, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityUserAuthorities.SECURITY_USER_AUTHORITIES);

        setId(id);
        setUserId(userId);
        setAuthorityId(authorityId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
