/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.tables.SecurityAuthorities;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityAuthoritiesRecord extends UpdatableRecordImpl<SecurityAuthoritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_authorities.ID</code>. Primary key
     */
    public SecurityAuthoritiesRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_authorities.NAME</code>. Authority
     * name e.g. ROLE_ADMIN
     */
    public SecurityAuthoritiesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.NAME</code>. Authority
     * name e.g. ROLE_ADMIN
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>security.security_authorities.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public SecurityAuthoritiesRecord setCreatedBy(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>security.security_authorities.CREATED_AT</code>. Time
     * when this row is created
     */
    public SecurityAuthoritiesRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.CREATED_AT</code>. Time
     * when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>security.security_authorities.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public SecurityAuthoritiesRecord setUpdatedBy(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>security.security_authorities.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public SecurityAuthoritiesRecord setUpdatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_authorities.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAuthoritiesRecord
     */
    public SecurityAuthoritiesRecord() {
        super(SecurityAuthorities.SECURITY_AUTHORITIES);
    }

    /**
     * Create a detached, initialised SecurityAuthoritiesRecord
     */
    public SecurityAuthoritiesRecord(ULong id, String name, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityAuthorities.SECURITY_AUTHORITIES);

        setId(id);
        setName(name);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
