/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.tables.SecurityUserRoles;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityUserRolesRecord extends UpdatableRecordImpl<SecurityUserRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_user_roles.ID</code>. Primary key
     */
    public SecurityUserRolesRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_roles.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_user_roles.USER_ID</code>. FK to
     * security_users
     */
    public SecurityUserRolesRecord setUserId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_roles.USER_ID</code>. FK to
     * security_users
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>security.security_user_roles.ROLE_ID</code>. FK to
     * security_roles
     */
    public SecurityUserRolesRecord setRoleId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_roles.ROLE_ID</code>. FK to
     * security_roles
     */
    public ULong getRoleId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>security.security_user_roles.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public SecurityUserRolesRecord setCreatedBy(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_roles.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>security.security_user_roles.CREATED_AT</code>. Time
     * when this row is created
     */
    public SecurityUserRolesRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_roles.CREATED_AT</code>. Time
     * when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>security.security_user_roles.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public SecurityUserRolesRecord setUpdatedBy(ULong value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_roles.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>security.security_user_roles.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public SecurityUserRolesRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_user_roles.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityUserRolesRecord
     */
    public SecurityUserRolesRecord() {
        super(SecurityUserRoles.SECURITY_USER_ROLES);
    }

    /**
     * Create a detached, initialised SecurityUserRolesRecord
     */
    public SecurityUserRolesRecord(ULong id, ULong userId, ULong roleId, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityUserRoles.SECURITY_USER_ROLES);

        setId(id);
        setUserId(userId);
        setRoleId(roleId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
