/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.tables.SecurityRoles;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityRolesRecord extends UpdatableRecordImpl<SecurityRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_roles.ID</code>. Primary key
     */
    public SecurityRolesRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_roles.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_roles.NAME</code>. Role name e.g.
     * ADMIN
     */
    public SecurityRolesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_roles.NAME</code>. Role name e.g.
     * ADMIN
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>security.security_roles.DESCRIPTION</code>.
     * Human-readable description
     */
    public SecurityRolesRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_roles.DESCRIPTION</code>.
     * Human-readable description
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>security.security_roles.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public SecurityRolesRecord setCreatedBy(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_roles.CREATED_BY</code>. ID of the
     * user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>security.security_roles.CREATED_AT</code>. Time when
     * this row is created
     */
    public SecurityRolesRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_roles.CREATED_AT</code>. Time when
     * this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>security.security_roles.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public SecurityRolesRecord setUpdatedBy(ULong value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_roles.UPDATED_BY</code>. ID of the
     * user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>security.security_roles.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public SecurityRolesRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_roles.UPDATED_AT</code>. Time when
     * this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityRolesRecord
     */
    public SecurityRolesRecord() {
        super(SecurityRoles.SECURITY_ROLES);
    }

    /**
     * Create a detached, initialised SecurityRolesRecord
     */
    public SecurityRolesRecord(ULong id, String name, String description, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityRoles.SECURITY_ROLES);

        setId(id);
        setName(name);
        setDescription(description);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
