/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import studio.ikara.security.jooq.tables.SecurityPermissions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityPermissionsRecord extends UpdatableRecordImpl<SecurityPermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.security_permissions.ID</code>. Primary key
     */
    public SecurityPermissionsRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>security.security_permissions.ID</code>. Primary key
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>security.security_permissions.CODE</code>. Permission
     * code e.g. Application_CREATE
     */
    public SecurityPermissionsRecord setCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>security.security_permissions.CODE</code>. Permission
     * code e.g. Application_CREATE
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>security.security_permissions.DESCRIPTION</code>.
     * Human-readable description
     */
    public SecurityPermissionsRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>security.security_permissions.DESCRIPTION</code>.
     * Human-readable description
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>security.security_permissions.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public SecurityPermissionsRecord setCreatedBy(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>security.security_permissions.CREATED_BY</code>. ID of
     * the user who created this row
     */
    public ULong getCreatedBy() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>security.security_permissions.CREATED_AT</code>. Time
     * when this row is created
     */
    public SecurityPermissionsRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>security.security_permissions.CREATED_AT</code>. Time
     * when this row is created
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>security.security_permissions.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public SecurityPermissionsRecord setUpdatedBy(ULong value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>security.security_permissions.UPDATED_BY</code>. ID of
     * the user who updated this row
     */
    public ULong getUpdatedBy() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>security.security_permissions.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public SecurityPermissionsRecord setUpdatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>security.security_permissions.UPDATED_AT</code>. Time
     * when this row is updated
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityPermissionsRecord
     */
    public SecurityPermissionsRecord() {
        super(SecurityPermissions.SECURITY_PERMISSIONS);
    }

    /**
     * Create a detached, initialised SecurityPermissionsRecord
     */
    public SecurityPermissionsRecord(ULong id, String code, String description, ULong createdBy, LocalDateTime createdAt, ULong updatedBy, LocalDateTime updatedAt) {
        super(SecurityPermissions.SECURITY_PERMISSIONS);

        setId(id);
        setCode(code);
        setDescription(description);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
