/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import studio.ikara.security.jooq.tables.SecurityAuthorities;
import studio.ikara.security.jooq.tables.SecurityPermissions;
import studio.ikara.security.jooq.tables.SecurityRolePermissions;
import studio.ikara.security.jooq.tables.SecurityRoles;
import studio.ikara.security.jooq.tables.SecurityUserAuthorities;
import studio.ikara.security.jooq.tables.SecurityUserRoles;
import studio.ikara.security.jooq.tables.SecurityUsers;
import studio.ikara.security.jooq.tables.records.SecurityAuthoritiesRecord;
import studio.ikara.security.jooq.tables.records.SecurityPermissionsRecord;
import studio.ikara.security.jooq.tables.records.SecurityRolePermissionsRecord;
import studio.ikara.security.jooq.tables.records.SecurityRolesRecord;
import studio.ikara.security.jooq.tables.records.SecurityUserAuthoritiesRecord;
import studio.ikara.security.jooq.tables.records.SecurityUserRolesRecord;
import studio.ikara.security.jooq.tables.records.SecurityUsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * security.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SecurityAuthoritiesRecord> KEY_SECURITY_AUTHORITIES_PRIMARY = Internal.createUniqueKey(SecurityAuthorities.SECURITY_AUTHORITIES, DSL.name("KEY_security_authorities_PRIMARY"), new TableField[] { SecurityAuthorities.SECURITY_AUTHORITIES.ID }, true);
    public static final UniqueKey<SecurityAuthoritiesRecord> KEY_SECURITY_AUTHORITIES_UK_SECURITY_AUTHORITIES_NAME = Internal.createUniqueKey(SecurityAuthorities.SECURITY_AUTHORITIES, DSL.name("KEY_security_authorities_uk_security_authorities_name"), new TableField[] { SecurityAuthorities.SECURITY_AUTHORITIES.NAME }, true);
    public static final UniqueKey<SecurityPermissionsRecord> KEY_SECURITY_PERMISSIONS_PRIMARY = Internal.createUniqueKey(SecurityPermissions.SECURITY_PERMISSIONS, DSL.name("KEY_security_permissions_PRIMARY"), new TableField[] { SecurityPermissions.SECURITY_PERMISSIONS.ID }, true);
    public static final UniqueKey<SecurityPermissionsRecord> KEY_SECURITY_PERMISSIONS_UK_SECURITY_PERMISSIONS_CODE = Internal.createUniqueKey(SecurityPermissions.SECURITY_PERMISSIONS, DSL.name("KEY_security_permissions_UK_SECURITY_PERMISSIONS_CODE"), new TableField[] { SecurityPermissions.SECURITY_PERMISSIONS.CODE }, true);
    public static final UniqueKey<SecurityRolePermissionsRecord> KEY_SECURITY_ROLE_PERMISSIONS_PRIMARY = Internal.createUniqueKey(SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS, DSL.name("KEY_security_role_permissions_PRIMARY"), new TableField[] { SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS.ID }, true);
    public static final UniqueKey<SecurityRolePermissionsRecord> KEY_SECURITY_ROLE_PERMISSIONS_UK_SECURITY_ROLE_PERMISSIONS = Internal.createUniqueKey(SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS, DSL.name("KEY_security_role_permissions_UK_SECURITY_ROLE_PERMISSIONS"), new TableField[] { SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS.ROLE_ID, SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS.PERMISSION_ID }, true);
    public static final UniqueKey<SecurityRolesRecord> KEY_SECURITY_ROLES_PRIMARY = Internal.createUniqueKey(SecurityRoles.SECURITY_ROLES, DSL.name("KEY_security_roles_PRIMARY"), new TableField[] { SecurityRoles.SECURITY_ROLES.ID }, true);
    public static final UniqueKey<SecurityRolesRecord> KEY_SECURITY_ROLES_UK_SECURITY_ROLES_NAME = Internal.createUniqueKey(SecurityRoles.SECURITY_ROLES, DSL.name("KEY_security_roles_UK_SECURITY_ROLES_NAME"), new TableField[] { SecurityRoles.SECURITY_ROLES.NAME }, true);
    public static final UniqueKey<SecurityUserAuthoritiesRecord> KEY_SECURITY_USER_AUTHORITIES_PRIMARY = Internal.createUniqueKey(SecurityUserAuthorities.SECURITY_USER_AUTHORITIES, DSL.name("KEY_security_user_authorities_PRIMARY"), new TableField[] { SecurityUserAuthorities.SECURITY_USER_AUTHORITIES.ID }, true);
    public static final UniqueKey<SecurityUserAuthoritiesRecord> KEY_SECURITY_USER_AUTHORITIES_UK1_USER_AUTHORITIES_USER_ID_AUTHORITY_ID = Internal.createUniqueKey(SecurityUserAuthorities.SECURITY_USER_AUTHORITIES, DSL.name("KEY_security_user_authorities_uk1_user_authorities_user_id_authority_id"), new TableField[] { SecurityUserAuthorities.SECURITY_USER_AUTHORITIES.USER_ID, SecurityUserAuthorities.SECURITY_USER_AUTHORITIES.AUTHORITY_ID }, true);
    public static final UniqueKey<SecurityUserRolesRecord> KEY_SECURITY_USER_ROLES_PRIMARY = Internal.createUniqueKey(SecurityUserRoles.SECURITY_USER_ROLES, DSL.name("KEY_security_user_roles_PRIMARY"), new TableField[] { SecurityUserRoles.SECURITY_USER_ROLES.ID }, true);
    public static final UniqueKey<SecurityUserRolesRecord> KEY_SECURITY_USER_ROLES_UK_SECURITY_USER_ROLES = Internal.createUniqueKey(SecurityUserRoles.SECURITY_USER_ROLES, DSL.name("KEY_security_user_roles_UK_SECURITY_USER_ROLES"), new TableField[] { SecurityUserRoles.SECURITY_USER_ROLES.USER_ID, SecurityUserRoles.SECURITY_USER_ROLES.ROLE_ID }, true);
    public static final UniqueKey<SecurityUsersRecord> KEY_SECURITY_USERS_PRIMARY = Internal.createUniqueKey(SecurityUsers.SECURITY_USERS, DSL.name("KEY_security_users_PRIMARY"), new TableField[] { SecurityUsers.SECURITY_USERS.ID }, true);
    public static final UniqueKey<SecurityUsersRecord> KEY_SECURITY_USERS_UK_SECURITY_USERS_EMAIL = Internal.createUniqueKey(SecurityUsers.SECURITY_USERS, DSL.name("KEY_security_users_uk_security_users_email"), new TableField[] { SecurityUsers.SECURITY_USERS.EMAIL }, true);
    public static final UniqueKey<SecurityUsersRecord> KEY_SECURITY_USERS_UK_SECURITY_USERS_USER_NAME = Internal.createUniqueKey(SecurityUsers.SECURITY_USERS, DSL.name("KEY_security_users_uk_security_users_user_name"), new TableField[] { SecurityUsers.SECURITY_USERS.USER_NAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SecurityRolePermissionsRecord, SecurityRolesRecord> FK1_ROLE_PERMISSIONS_ROLE_ID = Internal.createForeignKey(SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS, DSL.name("FK1_ROLE_PERMISSIONS_ROLE_ID"), new TableField[] { SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS.ROLE_ID }, Keys.KEY_SECURITY_ROLES_PRIMARY, new TableField[] { SecurityRoles.SECURITY_ROLES.ID }, true);
    public static final ForeignKey<SecurityRolePermissionsRecord, SecurityPermissionsRecord> FK2_ROLE_PERMISSIONS_PERMISSION_ID = Internal.createForeignKey(SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS, DSL.name("FK2_ROLE_PERMISSIONS_PERMISSION_ID"), new TableField[] { SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS.PERMISSION_ID }, Keys.KEY_SECURITY_PERMISSIONS_PRIMARY, new TableField[] { SecurityPermissions.SECURITY_PERMISSIONS.ID }, true);
    public static final ForeignKey<SecurityUserAuthoritiesRecord, SecurityUsersRecord> FK1_USER_AUTHORITIES_USER_ID_USERS_ID = Internal.createForeignKey(SecurityUserAuthorities.SECURITY_USER_AUTHORITIES, DSL.name("fk1_user_authorities_user_id_users_id"), new TableField[] { SecurityUserAuthorities.SECURITY_USER_AUTHORITIES.USER_ID }, Keys.KEY_SECURITY_USERS_PRIMARY, new TableField[] { SecurityUsers.SECURITY_USERS.ID }, true);
    public static final ForeignKey<SecurityUserAuthoritiesRecord, SecurityAuthoritiesRecord> FK2_USER_AUTHORITIES_AUTHORITY_ID_AUTHORITIES_ID = Internal.createForeignKey(SecurityUserAuthorities.SECURITY_USER_AUTHORITIES, DSL.name("fk2_user_authorities_authority_id_authorities_id"), new TableField[] { SecurityUserAuthorities.SECURITY_USER_AUTHORITIES.AUTHORITY_ID }, Keys.KEY_SECURITY_AUTHORITIES_PRIMARY, new TableField[] { SecurityAuthorities.SECURITY_AUTHORITIES.ID }, true);
    public static final ForeignKey<SecurityUserRolesRecord, SecurityUsersRecord> FK1_USER_ROLES_USER_ID = Internal.createForeignKey(SecurityUserRoles.SECURITY_USER_ROLES, DSL.name("FK1_USER_ROLES_USER_ID"), new TableField[] { SecurityUserRoles.SECURITY_USER_ROLES.USER_ID }, Keys.KEY_SECURITY_USERS_PRIMARY, new TableField[] { SecurityUsers.SECURITY_USERS.ID }, true);
    public static final ForeignKey<SecurityUserRolesRecord, SecurityRolesRecord> FK2_USER_ROLES_ROLE_ID = Internal.createForeignKey(SecurityUserRoles.SECURITY_USER_ROLES, DSL.name("FK2_USER_ROLES_ROLE_ID"), new TableField[] { SecurityUserRoles.SECURITY_USER_ROLES.ROLE_ID }, Keys.KEY_SECURITY_ROLES_PRIMARY, new TableField[] { SecurityRoles.SECURITY_ROLES.ID }, true);
}
