/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import studio.ikara.security.jooq.tables.SecurityAuthorities;
import studio.ikara.security.jooq.tables.SecurityPermissions;
import studio.ikara.security.jooq.tables.SecurityRolePermissions;
import studio.ikara.security.jooq.tables.SecurityRoles;
import studio.ikara.security.jooq.tables.SecurityUserAuthorities;
import studio.ikara.security.jooq.tables.SecurityUserRoles;
import studio.ikara.security.jooq.tables.SecurityUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Security extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security</code>
     */
    public static final Security SECURITY = new Security();

    /**
     * The table <code>security.security_authorities</code>.
     */
    public final SecurityAuthorities SECURITY_AUTHORITIES = SecurityAuthorities.SECURITY_AUTHORITIES;

    /**
     * The table <code>security.security_permissions</code>.
     */
    public final SecurityPermissions SECURITY_PERMISSIONS = SecurityPermissions.SECURITY_PERMISSIONS;

    /**
     * The table <code>security.security_role_permissions</code>.
     */
    public final SecurityRolePermissions SECURITY_ROLE_PERMISSIONS = SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS;

    /**
     * The table <code>security.security_roles</code>.
     */
    public final SecurityRoles SECURITY_ROLES = SecurityRoles.SECURITY_ROLES;

    /**
     * The table <code>security.security_user_authorities</code>.
     */
    public final SecurityUserAuthorities SECURITY_USER_AUTHORITIES = SecurityUserAuthorities.SECURITY_USER_AUTHORITIES;

    /**
     * The table <code>security.security_user_roles</code>.
     */
    public final SecurityUserRoles SECURITY_USER_ROLES = SecurityUserRoles.SECURITY_USER_ROLES;

    /**
     * The table <code>security.security_users</code>.
     */
    public final SecurityUsers SECURITY_USERS = SecurityUsers.SECURITY_USERS;

    /**
     * No further instances allowed
     */
    private Security() {
        super("security", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            SecurityAuthorities.SECURITY_AUTHORITIES,
            SecurityPermissions.SECURITY_PERMISSIONS,
            SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS,
            SecurityRoles.SECURITY_ROLES,
            SecurityUserAuthorities.SECURITY_USER_AUTHORITIES,
            SecurityUserRoles.SECURITY_USER_ROLES,
            SecurityUsers.SECURITY_USERS
        );
    }
}
