/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq;


import studio.ikara.security.jooq.tables.SecurityAuthorities;
import studio.ikara.security.jooq.tables.SecurityPermissions;
import studio.ikara.security.jooq.tables.SecurityRolePermissions;
import studio.ikara.security.jooq.tables.SecurityRoles;
import studio.ikara.security.jooq.tables.SecurityUserAuthorities;
import studio.ikara.security.jooq.tables.SecurityUserRoles;
import studio.ikara.security.jooq.tables.SecurityUsers;


/**
 * Convenience access to all tables in security.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>security.security_authorities</code>.
     */
    public static final SecurityAuthorities SECURITY_AUTHORITIES = SecurityAuthorities.SECURITY_AUTHORITIES;

    /**
     * The table <code>security.security_permissions</code>.
     */
    public static final SecurityPermissions SECURITY_PERMISSIONS = SecurityPermissions.SECURITY_PERMISSIONS;

    /**
     * The table <code>security.security_role_permissions</code>.
     */
    public static final SecurityRolePermissions SECURITY_ROLE_PERMISSIONS = SecurityRolePermissions.SECURITY_ROLE_PERMISSIONS;

    /**
     * The table <code>security.security_roles</code>.
     */
    public static final SecurityRoles SECURITY_ROLES = SecurityRoles.SECURITY_ROLES;

    /**
     * The table <code>security.security_user_authorities</code>.
     */
    public static final SecurityUserAuthorities SECURITY_USER_AUTHORITIES = SecurityUserAuthorities.SECURITY_USER_AUTHORITIES;

    /**
     * The table <code>security.security_user_roles</code>.
     */
    public static final SecurityUserRoles SECURITY_USER_ROLES = SecurityUserRoles.SECURITY_USER_ROLES;

    /**
     * The table <code>security.security_users</code>.
     */
    public static final SecurityUsers SECURITY_USERS = SecurityUsers.SECURITY_USERS;
}
