/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.security.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import studio.ikara.security.jooq.security.Security;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityNextId extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>security.security_next_id.result</code>.
     */
    public static final Parameter<Long> RESULT = Internal.createParameter("result", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public SecurityNextId() {
        super("security_next_id", Security.SECURITY, DSL.comment(""));

        addOutParameter(RESULT);
    }

    /**
     * Get the <code>result</code> parameter OUT value from the routine
     */
    public Long getResult() {
        return get(RESULT);
    }
}
