/*
 * This file is generated by jOOQ.
 */
package studio.ikara.security.jooq.security.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import studio.ikara.security.jooq.security.Security;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityGetCustomEpoch extends AbstractRoutine<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>security.security_get_custom_epoch.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public SecurityGetCustomEpoch() {
        super("security_get_custom_epoch", Security.SECURITY, DSL.comment(""), SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
    }
}
